..

diff --git a/kubernetes/apps/argocd/app/helmrelease.yaml b/kubernetes/apps/argocd/app/helmrelease.yaml
--- a/kubernetes/apps/argocd/app/helmrelease.yaml
+++ b/kubernetes/apps/argocd/app/helmrelease.yaml
@@ -96,13 +96,15 @@ spec:
                     DKF_ARGS+=("--source-path" "$PARAM_SOURCE_PATH")
                   fi
 
-                  for env_var in $(env | awk -F= '/^PARAM_VALUES_FILES_/ {print $1}'); do
-                    VALUES_FILE_PATH="$(printenv "$env_var")"
-                    if [[ ! -f "$VALUES_FILE_PATH" ]]; then
-                      echo "ERROR: values file '$VALUES_FILE_PATH' missing" >&2; exit 1
+                  while IFS='=' read -r k v; do
+                    VALUES_FILE_PATH="$v"
+                    if [[ -n "$VALUES_FILE_PATH" ]]; then
+                      if [[ ! -f "$VALUES_FILE_PATH" ]]; then
+                        echo "ERROR: values file '$VALUES_FILE_PATH' missing" >&2; exit 1
+                      fi
+                      DKF_ARGS+=("--values" "$VALUES_FILE_PATH")
                     fi
-                    DKF_ARGS+=("--values" "$VALUES_FILE_PATH")
-                  done
+                  done < <(env | awk -F= '/^PARAM_VALUES_FILES_/')
 
                   if [[ -n "$PARAM_VALUES" ]]; then
                     USER_VALUES_FILE_PATH="./__PLUGIN_USER_VALUES__.yaml"
@@ -161,12 +163,12 @@ spec:
                     if [[ -n "$KUBE_VERSION" ]]; then
                       HELM_ARGS+=("--kube-version" "$KUBE_VERSION")
                     fi
-                    for env_var in $(env | awk -F= '/^PARAM_OUTPUT_HELM_VALUES_FILES_/ {print $1}'); do
-                      HELM_VALUES_FILE_PATH=$(realpath "$OUTPUT_HELM_PATH/$(printenv "$env_var")")
+                    while IFS='=' read -r k v; do
+                      HELM_VALUES_FILE_PATH=$(realpath "$OUTPUT_HELM_PATH/$v")
                       if [[ -f "$HELM_VALUES_FILE_PATH" ]]; then
                         HELM_ARGS+=("--values" "$HELM_VALUES_FILE_PATH")
                       fi
-                    done
+                    done < <(env | awk -F= '/^PARAM_OUTPUT_HELM_VALUES_FILES_/')
                     if [[ -n "$KUBE_API_VERSIONS" ]]; then
                       IFS=',' read -ra KUBE_API_VERSIONS_ARRAY <<< "$KUBE_API_VERSIONS"
                       for KUBE_API_VERSION in "${KUBE_API_VERSIONS_ARRAY[@]}"; do
